"""Static mobile/layout guardrails for the browser game.

The goal is not pixel-perfect visual QA. It catches the regressions that have
hurt the game most often: tiny click targets, missing landscape support, hidden
overflow, and panels that cannot scroll on phones/tablets.
"""

from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
JS = (ROOT / "www" / "index.js").read_text(encoding="utf-8") + "\n" + (ROOT / "www" / "first-person-world.js").read_text(encoding="utf-8")
CSS = (ROOT / "www" / "index.css").read_text(encoding="utf-8") + "\n" + (ROOT / "www" / "first-person-world.css").read_text(encoding="utf-8")
HTML = (ROOT / "www" / "index.html").read_text(encoding="utf-8")
RELEASE_QUALITY = (ROOT / "www" / "release-quality.js").read_text(encoding="utf-8")


REQUIRED = {
    "shared hitbox standard": [
        "normalizeClickableSurface",
        "hitbox-standard",
        "isInsideVisibleHitbox",
        "getMapTaskVisibleHitboxes",
        "button.hitbox-standard::after",
        "pointer-events:none",
    ],
    "mobile landscape scroll": [
        "@media (orientation: landscape)",
        "overflow-y:auto",
        "height:auto",
        "100svh",
    ],
    "device zoom": [
        "deviceScreenZoomed",
        "toggleDeviceScreenZoom",
        "device-zoomed",
        "device-zoom-toggle",
    ],
    "live route map": [
        "buildLiveVoyageRouteMotionOverlay",
        "live-route-motion",
        "SOG",
        "TCPA",
    ],
    "cache bumped": [
        "index.js?v=197",
        "index.css?v=171",
        "release-quality.js?v=10",
    ],
    "4k dynamic background": [
        "__bgRenderScale",
        "__bgCanvasQuality",
        "4k-dpr",
        "getDynamicSceneTrafficOverlay",
        "scene-parallax-layer",
        "traffic-ship",
    ],
    "4k visual polish": [
        "getScene4KOverlay",
        "live-4k-grade",
        "live-4k-ecdis-grid",
        "live-4k-stormglass",
        "phoneGlass4K",
        "premiumCard4K",
    ],
    "4k shodb chart maps": [
        "buildShodbChartIndexOverlay",
        "buildWorldShodbChartIndexOverlay",
        "chart-index-sheet-layer",
        "shodb-style",
        "MARMARA DENIZI",
    ],
    "advanced map chain ui": [
        "map-chain-panel",
        "ecdis-control-overlay",
        "buildEcdisChartControlOverlay",
        "runMapTaskReplay",
        "getClickedWorldChartIndexSheet",
    ],
    "expanded map workspace": [
        "#map-box{background:var(--navy2);border:1px solid var(--border);border-radius:12px;width:min(1920px,calc(100vw - 8px));height:calc(100dvh - 8px);max-height:calc(100dvh - 8px);padding:6px;position:relative;overflow:hidden;",
        "overscroll-behavior:contain",
        "#map-world-view{display:flex;flex:1 1 auto;min-height:0;flex-direction:column;}",
        "#map-svg{width:100%;height:calc(100dvh - 126px);",
        "#port-chart-box{border:1px solid var(--border2);border-radius:10px;background:rgba(7,19,36,0.55);padding:7px;display:grid;",
        "#port-chart-svg{width:100%;height:100%;min-height:420px;",
        "#port-chart-taskbox{position:relative;left:auto;right:auto;bottom:auto;width:100%;",
        'preserveAspectRatio="xMidYMid slice"',
        "map-task-touch-area",
        "showMapTapFeedback",
        "focusCurrentMapTask",
        "touch-action:pan-y pinch-zoom",
        "#map-files{border:1px solid var(--border2);border-radius:8px;background:rgba(7,19,36,0.55);padding:6px;max-height:none;",
    ],
    "political world atlas": [
        "political-atlas",
        "WORLD_ATLAS_COUNTRIES",
        "natural-earth-atlas",
        "world-country",
        "ne-country",
        "world-country-line",
        "atlas-label",
        "country-label",
        "worldSeaGrad",
    ],
    "always available notes glossary": [
        "onclick=\"openNotes()\"",
        "onclick=\"openGlossary()\"",
        "function openGlossary()",
        "notesTab = 'sozluk'",
        "ui.glossary",
    ],
    "intro menu pages": [
        "home-screen",
        "home-page-play",
        "home-page-options",
        "home-page-premium",
        "setAppScreen",
        "openSetupScreen",
        "openGameScreen",
        "intro-menu-shell",
        "intro-menu-tabs",
        "intro-page-play",
        "intro-page-options",
        "intro-page-premium",
        "setIntroMenuPage",
        "intro-premium-card",
        "intro-audio-card",
        "sound-option-btn",
        "game-settings-vibration-btn",
        "toggleVibration",
        "navigator.vibrate",
        "audio-mixer",
        "game-settings-btn",
        "game-settings-panel",
        "game-settings-grid",
        "exitToHomeFromGame",
    ],
    "3d and first person control": [
        "ship-control-stage",
        "ship-control-pad",
        "shipwalk-avatar",
        "handleShipWalkKeydown",
        "bridge-walk-3d-scene",
        "BRIDGE_WALK_STATIONS",
        "openBridgeWalkDevice",
        "SHIP_OPERATION_MODES",
        "operation-walk-stage",
        "openShipOperation3D",
        "openCurrentSceneControlWalk",
        "shipwalk: true",
        "gfx-control",
        "scene-control-player",
        "interactSceneControlStation",
        "bridge3d-control-launcher",
        "walkAvatarMotion",
        "getWalkAvatarMotionClass",
        "bridge3d-live-cadet",
        "WALK_MISSION_CHAINS",
        "queueWalkMission",
        "walk-mission-panel",
        "BRIDGE_WALK_NPCS",
        "bridge3d-npc",
        "ship-control-door",
        "firstPersonPlayer",
        "fp-hotspot",
        "fp-world",
        "handleFirstPersonKeydown",
        "openFirstPersonMode",
        "firstPersonArea",
        "FIRST_PERSON_AREA_DEFS",
        "setFirstPersonArea",
        "fp-body",
        "fpWalkBob",
        "firstPersonPointer",
        "handleFirstPersonPointerDown",
        "moveFirstPersonTowardScreen",
        "fp-minimap",
        "getFirstPersonDirectorTarget",
        "getFirstPersonDirectorHtml",
        "fp-director",
        "objective",
        "firstPersonInput",
        "tickFirstPersonMove",
        "startFirstPersonMove",
        "setFirstPersonDestination",
        "fp-destination",
        "renderFirstPersonFallback",
        "ensureFirstPersonHost",
        "renderFirstPersonBootScreen",
        "FIRST_PERSON_ROAMING_NPCS",
        "getFirstPersonRoamingNpcs",
        "firstPersonNpcTimer",
        "roaming",
        "fpNpcDrift",
        "openFirstPersonSeaLook",
        "fp-sea-look",
        "fp-deck-view",
        "deck-sea-port",
        "deck-bow-view",
        "bridge-wing-port",
        "bridge-wing-stbd",
        "bridge-binoculars",
        "openFirstPersonBinocularLook",
        "fp-binocular",
        "renderFirstPersonModeUnsafe",
        "fp-fallback-shell",
        "firstperson-btn",
        "area-engine",
        "area-deck",
        "area-cabin",
        "area-mess",
        "firstperson-panel",
    ],
    "first person WebGL world": [
        "__GUVERTE_FP3D",
        "new T.PerspectiveCamera",
        "new T.WebGLRenderer",
        "updateMovement",
        "createNpc",
        "fp3d-stick",
        "fp3d-use",
        "fp3d-dialogue",
        "GMDSS ODASI",
        "YÜK KONTROL ODASI",
        "first-person-world.js?v=2",
        "first-person-world.css?v=2",
    ],
    "intro route selector": [
        "route-select-grid",
        "route-card",
        "renderVoyageRouteSelector",
        "setSelectedVoyageRoute",
        "MAJOR_TRADE_ROUTE_KEYS",
    ],
    "new voyage route pack": [
        "ADDITIONAL_NAVIGATION_ROUTES",
        "us_pnw_asia_grain",
        "australia_japan_lng",
        "gulf_europe_crude_cape",
        "blacksea_india_bulk",
        "north_europe_canada_stlawrence",
        "asia_australia_container",
    ],
    "setup ship selection tab": [
        "data-intro-tab=\"ship\"",
        "openShipSelectScreen",
        "ensureShipSelectScreen",
        "ship-choice-summary",
        "ship-tab-card",
        "renderShipChoiceSummary",
        "introMenuPage === 'ship'",
    ],
    "launch readiness spine": [
        "getSetupReadinessDetails",
        "getPremiumAccessSummary",
        "setup-readiness",
        "renderSetupOnboardingGuide",
        "Kalkis icin hazir",
    ],
    "creator preset guard": [
        "normalizePlayerAppearance",
        "getCreatorHairPool",
        "renderCreatorIntegrityNote",
        "Preset korumasi aktif",
    ],
    "mission polish spine": [
        "getGamePolishStatus",
        "maybeQueueMapPracticeFromScene",
        "getRemedialMapTaskForScene",
        "Harita/ECDIS tekrari acildi",
    ],
    "retention loop": [
        "RETENTION_KEY",
        "SEASON_CATALOG",
        "DAILY_MISSION_POOL",
        "WEEKLY_MISSION_POOL",
        "renderRetentionPanel",
        "home-retention-panel",
        "recordLeaderboardScore",
        "retention-panel",
    ],
    "cinema exit and ad removal": [
        "cinema-exit-btn",
        "toggleCinemaMode(false)",
        "ADS_REMOVAL_PRODUCT_ID",
        "ADS_REMOVAL_PRICE_LABEL",
        "openAdsRemovalPurchase",
        "restoreAdsRemovalPurchase",
        "adsRemoved",
    ],
    "clean gameplay ui": [
        "stats-summary",
        "toggleStatsExpanded",
        "more-tools-panel",
        "toggleMoreTools",
        "cinema-mode",
        "toggleCinemaMode",
        "primary-tool",
        "CLEAN_HUD_KEY",
        "PERFORMANCE_MODE_KEY",
        "setCleanHudMode",
        "data-clean-hud-toggle",
        "data-performance-mode-toggle",
        "clean-hud",
        "performance-mode",
        "release-hardening-summary",
        "getReleaseHardeningChecks",
    ],
    "mobile creator portrait fit": [
        "creator-mobile-portrait-fit",
        ".creator-preview-stage .portrait-composite.preview",
        "width:min(48vw,190px)",
        "scale(.74)",
    ],
    "mobile fit overhaul": [
        "mobile-fit-overhaul",
        "body.screen-game{height:100dvh;overflow:hidden;}",
        "#story{flex:1 1 auto;min-height:0;overflow:auto;",
        "#choices{flex:0 0 auto;display:grid;grid-template-columns:1fr;",
        "mobile-landscape-fit",
        "body.screen-game{height:100svh;overflow:hidden;}",
        "#map-box,#devices-box,#notes-box,#journal-box,#colreg-box",
    ],
    "ultra 4k expansion": [
        "ULTRA_4K_ROUTE_EXPANSION",
        "live-4k-bridge-reflection",
        "live-4k-port-haze",
        "live-4k-wave-burst",
        "traffic-research",
        "traffic-roro",
    ],
    "cinematic scene pack": [
        "CINEMATIC_SCENES",
        "injectCinematicScenes",
        "getCinematicOverlay",
        "setupCinematicSceneFlow",
        "scene-cinematic-",
        "cinematic-shot",
        "cinematic-beat-strip",
        "cinematic-text-flow",
        "cinematic-controls",
        "cinematic-props",
        "cin-prop pilot-boat",
    ],
    "professional graphics package": [
        "getProfessionalGraphicsOverlay",
        "pro-graphics-overlay",
        "pro-device-row",
        "pro-atlas-chip",
        "pro-preset-chip",
        "pro-ops-depth",
        "suezConvoy",
        "panamaLock",
        "mooringSnapback",
        "tankerManifold",
        "researchRov",
        "route3d",
        "3D ROV / DP arastirma",
    ],
}


def main() -> int:
    blob = "\n".join([JS, CSS, HTML, RELEASE_QUALITY])
    missing: list[str] = []
    for group, needles in REQUIRED.items():
        for needle in needles:
            if needle not in blob:
                missing.append(f"{group}: {needle}")
    removed_creator_controls = [
        "id=\"creator-haircolor\"",
        "id=\"creator-eye\"",
        "id=\"creator-uniform\"",
        "renderCreatorRow('creator-haircolor'",
        "renderCreatorRow('creator-eye'",
        "renderCreatorRow('creator-uniform'",
    ]
    for needle in removed_creator_controls:
        if needle in blob:
            missing.append(f"creator color controls removed: unexpected {needle}")
    if missing:
        print("MOBILE_LAYOUT_QA_FAIL")
        for item in missing:
            print(f"- {item}")
        return 1
    print("MOBILE_LAYOUT_QA_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
